name: Release

on:
  push:
    tags:
      - '*'

jobs:
  github-release:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "${{ steps.get_version.outputs.VERSION }}" \
            --generate-notes

  linux-binary:
    name: 'Upload Binary for Linux'
    runs-on: ubuntu-latest
    needs: github-release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependent packages
        run: sudo apt install -y musl-tools

      - run: rustup update stable
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv target/x86_64-unknown-linux-musl/release/mamegrep mamegrep-${{ needs.github-release.outputs.version }}.x86_64-unknown-linux-musl
          gh release upload ${{ needs.github-release.outputs.version }} \
            mamegrep-${{ needs.github-release.outputs.version }}.x86_64-unknown-linux-musl

  macos-binary:
    name: 'Upload Binary for MacOS'
    runs-on: macos-latest
    needs: github-release
    strategy:
      matrix:
        target: ["x86_64-apple-darwin", "aarch64-apple-darwin"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - run: rustup update stable
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --target=${{ matrix.target }}

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv target/${{ matrix.target }}/release/mamegrep mamegrep-${{ needs.github-release.outputs.version }}.${{ matrix.target }}
          gh release upload ${{ needs.github-release.outputs.version }} \
            mamegrep-${{ needs.github-release.outputs.version }}.${{ matrix.target }}

  publish-crates:
    name: 'Publish to crates.io'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - run: rustup update stable

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

